### ISSUE TITLE
[bug] Click on the list doesn't select the item

### ISSUE THREAD

**Issue by MartinFreire** [avallete/ag-grid-autocomplete-editor#26] opened 2019-05-21 14:55 UTC
I've been trying the new feature [#23](https://github.com/avallete/ag-grid-autocomplete-editor/issues/23) but now I noticed that if you click on the list element it doesn't select it.

**Comment by avallete** [comment] 2019-05-22 07:15
Yep it's strange, but actually the item seem to be selected. The issue is that the 'input' field stay blank, and the editor doesn't stop edit mode after item has been clicked.

If you click away, you will se the value of your selected item on the cell.

It come from the default `onSelect` parameter who doesn't call `cellEditor.destroy();` anymore in it.
Keyboard destroy() are properly handled into `handleTabEvent`, mouse event may need the same kind of default handling.

As a workaround, for the moment you can call `cellEditor.destroy()` into your `onSelect` handler if you have one. I'll fix this bug ASAP.

**Comment by avallete** [comment] 2019-05-22 09:33
Should be fixed on v1.2.1

Please feel free to reopen to report any issue

**Closed by avallete** 2019-05-22 09:33 UTC
