### ISSUE TITLE
Everytime the user enters data, [object object] gets written

### ISSUE THREAD

**Issue by janhesters** [avallete/ag-grid-autocomplete-editor#15] opened 2019-05-03 12:17 UTC
Hi avallete, great package 👌🏻 Thank you for creating it.

I have the following problem: When the user enters a value, never writes the value, but

```js
{
  value: <entered value>,
  label: <entered value>
}
```

[I'd also like any value to be entered](https://github.com/avallete/ag-grid-autocomplete-editor/issues/14) (not only the auto complete suggestions).

Here is my code:

```js
function contactInformationFormatter(params) {
  if (params.value) {
    // Me trying to extract the value so that not `[object object]` gets returned.
    return strings[params.value] || params.value.value || params.value;
  }
  return '';
}

function ContactList({
  autoSuggestions,
  contacts,
  onCellValueChanged,
  searchValue,
}) {
  const columnDefs = R.map(
    R.pipe(x => ({
      headerName: strings[x.name],
      field: x.name,
      valueFormatter: contactInformationFormatter,
      cellEditor: keysThatShouldHaveAutoSuggestions.includes(x.name)
        ? AutocompleteSelectCellEditor
        : componentToCellEditors[x.component],
      cellEditorParams:
        x.component === 'select'
          ? cellEditorParams[x.name]
          : keysThatShouldHaveAutoSuggestions.includes(x.name)
          ? {
              selectData: autoSuggestions[x.name].map(x => ({
                value: x,
                label: x,
              })),
            }
          : null,
      getQuickFilterText: function(params) {
        return x.component === 'select' ? null : params.value;
      },
      cellClassRules: {
        'search-value-found':
          'api.gridOptionsWrapper.gridOptions.quickFilterText && x.toLowerCase().includes(api.gridOptionsWrapper.gridOptions.quickFilterText)',
      },
    })),
    contactInformationCells
  );
```

Do you have any idea, what I'm doing wrong?

**Comment by avallete** [comment] 2019-05-03 13:59
For the 'any' option, I created another issue to ask about this feature request, and formalize what need to be done, feel free to participate and give your opinion about the described implementation: https://github.com/avallete/ag-grid-autocomplete-editor/issues/16


For your problem, I don't spot any obvious error apart from the (`return strings[params.value] `) into the Formatter who look very strange to me. Since `params.value` will contain an object of type `{value: x, label: y}`. You probably want to do `params.value.value` to select your actual value.

Maybe try to post an basic example with some data on https://stackblitz.com so I will be able to help you better.

**Comment by janhesters** [comment] 2019-05-05 15:44
I answered on that issue, too.

I have `strings[params.value]` as part of some other selects, where I use i18n (but they do not get their values from this package).

**Comment by avallete** [comment] 2019-05-05 17:35
Ok, so if I understood the first 'strings[params.value]' return `undefined`, so after that it's the `params.value.value` who are sent ?

If that the case, that should work since it's what I do into my own examples:

```
   valueFormatter: (params) => {
       if (params.value) {
           return params.value.label || params.value.value || params.value;
       }
       return "";
   },
```

But, as I said before, there is too much going on into your code to me. The multiples loop and imbricated ternary confuse me a bit.

Could you please try to `console.log(params)` inside the `valueFormatter` to see what is returned by the cellEditor ? Or as I said before, please try to reproduce your bug on a minimal working code example into https://stackblitz.com/ .

**Comment by avallete** [comment] 2019-05-10 09:17
In the mean time, I close the issue.

Feel free to reopen it with minimal working code error if your problem persist.

**Closed by avallete** 2019-05-10 09:17 UTC
