### ISSUE TITLE
On selecting some value from auto complete then again editing that it is clearing last value selected

### ISSUE THREAD

**Issue by ajayupreti** [avallete/ag-grid-autocomplete-editor#65] opened 2020-05-04 06:01 UTC
on selecting some value from autocomplete then again editing that it is clearing the value. 
I want my last value to be selected there

**Comment by avallete** [comment] 2020-05-05 03:44
Duplicate of #49, closing this issue and re-opening the other one to keep history.

**Closed by avallete** 2020-05-05 03:44 UTC
